os: Visual Studio 2017

platform: x64

configuration: Release

skip_tags: true

environment:
    MINICONDA_ROOT: C:\Miniconda37-x64

install:
  - ps: $env:COMMIT_TIMESTAMP = git log -1 --pretty=format:%ct

  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
  
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" root
  - cmd: conda config --append channels conda-forge
  - cmd: conda create -y --name default --clone root
  - cmd: conda install -y -q conda-build
  
  - cmd: cd C:\ && git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && bootstrap-vcpkg.bat && cd %APPVEYOR_BUILD_FOLDER%
  
build_script:
  - cmd: conda metapackage pairinteraction-dependencies %COMMIT_TIMESTAMP% --no-anaconda-upload --dependencies pyqt numpy scipy psutil pint pyzmq
  - cmd: conda deactivate
  
  - cmd: C:\vcpkg\vcpkg install sqlite3:x64-windows eigen3:x64-windows gsl:x64-windows zeromq:x64-windows

after_build:
  - call "%MINICONDA_ROOT%\Scripts\activate.bat" default
  - cmd: conda clean -y -a
  - cmd: conda install -y -q pairinteraction-dependencies --use-local
  - cmd: md conda-export\noarch
  - cmd: md conda-export\win-64
  - cmd: move %MINICONDA_ROOT%\pkgs\*.tar.bz2 conda-export\win-64
  - cmd: conda list -e > conda-spec-file.txt
  - cmd: activate root
  - cmd: conda index conda-export\noarch
  - cmd: conda index conda-export\win-64
  - cmd: 7z a -tzip python-packages-windows-x86_64.zip conda-export conda-spec-file.txt > nul
    
  - cmd: C:\vcpkg\vcpkg export sqlite3:x64-windows eigen3:x64-windows gsl:x64-windows zeromq:x64-windows --raw
  - cmd: move C:\vcpkg\vcpkg-export-* vcpkg-export
  - cmd: 7z a -tzip cpp-libraries-windows-x86_64.zip vcpkg-export > nul
  
artifacts:
  - path: cpp-libraries-windows-x86_64.zip
    name: cpp-libraries-windows-x86_64
  - path: python-packages-windows-x86_64.zip
    name: python-packages-windows-x86_64

deploy:
  - provider: GitHub
    release: $(COMMIT_TIMESTAMP)
    auth_token: $(GH_TOKEN)
    artifact: cpp-libraries-windows-x86_64, python-packages-windows-x86_64
    force_update: true
    on:
      branch: master
